---
# tasks file for adoptopenjdk | Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Install python3-apt
  ansible.builtin.apt:
    name: python3-apt
    state: present
    force_apt_get: yes
    update_cache: yes

- name: Debian/Ubuntu Family | Installing {{ adoptopenjdk_pre_reqs_debian }} for {{ adoptopenjdk_app_name }}
  ansible.builtin.apt:
    name: "{{ adoptopenjdk_pre_reqs_debian }}"
    state: "{{ adoptopenjdk_pre_reqs_debian_desired_state }}"
    force_apt_get: yes

- name: Debian/Ubuntu Family | Add gpg signing key for {{ adoptopenjdk_app_name }}
  ansible.builtin.apt_key:
    url: "{{ adoptopenjdk_repo_debian_gpg_key }}"
    state: present
    keyring: "{{ adoptopenjdk_repo_debian_gpg_keyring_file }}"

- name: Debian/Ubuntu Family | Adding repository {{ adoptopenjdk_repo_debian }}
  ansible.builtin.apt_repository:
    repo: "{{ adoptopenjdk_repo_debian }}"
    codename: "{{ ansible_lsb['codename'] }}"
    filename: "{{ adoptopenjdk_repo_debian_filename }}"
    state: "{{ adoptopenjdk_repo_debian_desired_state }}"
    update_cache: yes

- name: Debian/Ubuntu Family | Installing {{ adoptopenjdk_app_name }}
  ansible.builtin.apt:
    name: "{{ adoptopenjdk_app_name }}"
    state: "{{ adoptopenjdk_desired_state }}"
    force_apt_get: yes
    update_cache: yes
